'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports Entidades
Partial Public Class CampeonatosPelotaEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CampeonatosPelotaEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Campeonatos() As DbSet(Of Campeonato)
    Public Overridable Property Frontons() As DbSet(Of Fronton)
    Public Overridable Property Pelotaris() As DbSet(Of Pelotari)
    Public Overridable Property Provincias() As DbSet(Of Provincia)

End Class
