'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Campeonato
    Public Property Año As Integer
    Public Property IdCampeon As String
    Public Property IdSubCampeon As String
    Public Property TantosSubCampeon As Integer
    Public Property IdFronton As String

    Public Overridable Property Fronton As Fronton
    Public Overridable Property Campeon As Pelotari
    Public Overridable Property SubCampeon As Pelotari

End Class
