'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pelotari
    Public Property Id As String
    Public Property Nombre As String
    Public Property Localidad As String
    Public Property IdProvincia As String

    Public Overridable Property CampeonatosCampeon As ICollection(Of Campeonato) = New HashSet(Of Campeonato)
    Public Overridable Property CampeonatosSubCampeon As ICollection(Of Campeonato) = New HashSet(Of Campeonato)
    Public Overridable Property Provincia As Provincia

End Class
